name: sane_ai_4
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pip
  - cudatoolkit=11.8.*
  - cudnn=8.9.*
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - attrs=22.2.0
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=6.0.0
  - brotlipy=0.7.0
  - ca-certificates
  - certifi
  - cffi=1.14.6
  - charset-normalizer=2.1.1
  - comm=0.1.2
  - cryptography=39.0.0
  - debugpy=1.6.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.2.0
  - flit-core=3.8.0
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.10.2
  - ipykernel=6.21.0
  - ipython=8.9.0
  - ipython_genutils=0.2.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter_client=8.0.1
  - jupyter_core=5.2.0
  - jupyter_events=0.6.3
  - jupyter_server=2.1.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=3.5.2
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.19.0
  - ld_impl_linux-64=2.40
  - libffi=3.3
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libzlib=1.2.13
  - markupsafe=2.1.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - nbclassic=0.4.8
  - nbclient=0.7.2
  - nbconvert=7.2.9
  - nbconvert-core=7.2.9
  - nbconvert-pandoc=7.2.9
  - nbformat=5.7.3
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - openssl=1.1.1t
  - packaging=23.0
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - platformdirs=2.6.2
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.14.0
  - pyopenssl=23.0.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.4
  - python_abi=3.9
  - pyyaml=6.0
  - pyzmq=25.0.0
  - readline=8.1.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.0
  - setuptools=66.1.1
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.6.2
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.0
  - wheel=0.38.4
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.12.0
  - zlib=1.2.13
  - pip:
    - tensorflow==2.15.*
    - tensorflow-probability==0.23.*
    - tensorboard==2.15.*
    - tensorflow-estimator==2.15.*
    - keras==2.15.*
    - absl-py==1.4.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - apscheduler==3.10.4
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - backports-zoneinfo==0.2.1
    - boto3==1.26.59
    - botocore==1.29.59
    - browser-cookie3==0.19.1
    - cachetools==5.2.1
    - click==8.0.4
    - cloudpickle==2.2.1
    - cycler==0.11.0
    - dateparser==1.1.6
    - distlib==0.3.6
    - empyrical==0.5.5
    - exceptiongroup==1.1.3
    - farama-notifications==0.0.4
    - filelock==3.9.0
    - flatbuffers==23.3.3
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2023.1.0
    - gast==0.4.0
    - gdown==4.6.0
    - glassnode==0.0.2
    - google-api-core==2.11.0
    - google-auth==2.16.0
    - google-auth-oauthlib==0.4.6
    - google-cloud-core==2.3.2
    - google-cloud-storage==2.8.0
    - google-crc32c==1.5.0
    - google-pasta==0.2.0
    - google-resumable-media==2.5.0
    - googleapis-common-protos==1.59.0
    - greenlet==2.0.2
    - grpcio==1.43.0
    - gym==0.26.*
    - gym-notices==0.0.8
    - gym-unity==0.27.0
    - gymnasium==0.29.*
    - gymnasium-notices==0.0.1
    - h11==0.14.0
    - h5py==3.7.0
    - imageio==2.24.0
    - iso8601==1.1.0
    - jeepney==0.8.0
    - jmespath==1.0.1
    - joblib==1.2.0
    - jwt==1.3.1
    - kiwisolver==1.4.4
    - libclang==15.0.6.1
    - lxml==4.9.2
    - lz4==4.0.2
    - markdown==3.4.1
    - markdown-it-py==3.0.0
    - matplotlib==3.7.*
    - mdurl==0.1.2
    - mlagents-envs==0.30.*
    - modin==0.18.1
    - msgpack==1.0.4
    - multidict==6.0.4
    - networkx==3.0
    - numpy==1.23.*
    - oauthlib==3.2.2
    - opencv-python==4.8.*
    - opt-einsum==3.3.0
    - outcome==1.2.0
    - pandas==2.0.*
    - pandas-datareader==0.10.0
    - pandas-ta==0.3.14b0
    - pathspec==0.10.3
    - patsy==0.5.3
    - pillow==10.0.*
    - playwright==1.38.0
    - protobuf==3.19.6
    - pyarrow==15.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybit==5.3.0
    - pycryptodomex==3.19.0
    - pyee==9.0.4
    - pyfolio==0.9.2
    - pyparsing==3.0.9
    - python-binance==1.0.16
    - python-dotenv==1.0.0
    - pytz==2023.3.post1
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.4.1
    - ray==2.6.*
    - regex==2022.10.31
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rich==13.7.0
    - rsa==4.9
    - s3transfer==0.6.0
    - sanpy==0.11.4
    - scikit-image==0.19.3
    - scikit-learn==1.3.*
    - scipy==1.11.*
    - seaborn==0.12.*
    - selenium==4.13.0
    - sortedcontainers==2.4.0
    - statsmodels==0.13.5
    - tabulate==0.8.10
    - tensor-annotations==2.0.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6
    - termcolor==2.2.0
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - torch==2.0.*
    - torchaudio==2.0.*
    - torchvision==0.15.*
    - tqdm==4.65.*
    - trio==0.22.2
    - trio-websocket==0.11.1
    - typer==0.9.0
    - tzdata==2022.7
    - tzlocal==4.2
    - ujson==5.7.0
    - virtualenv==20.17.1
    - webdriver-manager==4.0.1
    - websockets==10.4
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - wsproto==1.2.0
    - yarl==1.8.2
