name: sane_ai_4
channels:
  - conda-forge
  - defaults
dependencies:
  # (Keep your existing conda dependencies here)
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anyio=3.6.2=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb9d737c_3
  # ... (rest of your conda dependencies)
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - apscheduler==3.10.4
    - astunparse==1.6.3
    - async-timeout==4.0.2
    # Removed backports-zoneinfo==0.2.1
    - boto3==1.26.59
    - botocore==1.29.59
    - browser-cookie3==0.19.1
    - cachetools==5.2.1
    - click==8.0.4
    - cloudpickle==2.2.1
    - cycler==0.11.0
    - dateparser==1.1.6
    - distlib==0.3.6
    - empyrical==0.5.5
    - exceptiongroup==1.1.3
    - farama-notifications==0.0.4
    - filelock==3.9.0
    - flatbuffers==23.3.3
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2023.1.0
    - gast==0.4.0
    - gdown==4.6.0
    - glassnode==0.0.2
    - google-api-core==2.11.0
    - google-auth==2.16.0
    - google-auth-oauthlib==0.4.6
    - google-cloud-core==2.3.2
    - google-cloud-storage==2.8.0
    - google-crc32c==1.5.0
    - google-pasta==0.2.0
    - google-resumable-media==2.5.0
    - googleapis-common-protos==1.59.0
    - greenlet==2.0.2
    - grpcio==1.43.0
    - gym==0.21.0
    - gym-notices==0.0.8
    - gym-unity==0.27.0
    - gymnasium==0.26.3
    - gymnasium-notices==0.0.1
    - h11==0.14.0
    - h5py==3.7.0
    - imageio==2.24.0
    - iso8601==1.1.0
    - jeepney==0.8.0
    - jmespath==1.0.1
    - joblib==1.2.0
    - jwt==1.3.1
    - keras==2.11.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - libclang==15.0.6.1
    - lxml==4.9.2
    - lz4==4.0.2
    - markdown==3.4.1
    - markdown-it-py==3.0.0
    - matplotlib==3.5.3
    - mdurl==0.1.2
    - mlagents-envs==0.27.0
    - modin==0.18.1
    - msgpack==1.0.4
    - multidict==6.0.4
    - networkx==3.0
    - numpy==1.23.3
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cudnn-cu11==8.6.0.163
    - oauthlib==3.2.2
    - opencv-python==4.7.0.71  # Updated to non-yanked version
    - opt-einsum==3.3.0
    - outcome==1.2.0
    - pandas==1.5.3
    - pandas-datareader==0.10.0
    - pandas-ta==0.3.14b0
    - pathspec==0.10.3
    - patsy==0.5.3
    - pillow==9.2.0
    - playwright==1.38.0
    - protobuf==3.19.6
    - pyarrow==15.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybit==5.3.0
    - pycryptodomex==3.19.0
    - pyee==9.0.4
    - pyfolio==0.9.2
    - pyparsing==3.0.9
    - python-binance==1.0.16
    - python-dotenv==1.0.0
    # Removed pytz==2023.3.post1
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.4.1
    - ray==2.3.1
    - regex==2022.10.31
    # Removed requests==2.28.1
    - requests-oauthlib==1.3.1
    - rich==13.7.0
    - rsa==4.9
    - s3transfer==0.6.0
    - sanpy==0.11.4
    - scikit-image==0.19.3
    - scikit-learn==1.2.0
    - scipy==1.9.1
    - seaborn==0.12.2
    - selenium==4.13.0
    - sortedcontainers==2.4.0
    - statsmodels==0.13.5
    - tabulate==0.8.10
    - tensor-annotations==2.0.2
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.32.0
    - tensorflow-probability==0.19.0
    - termcolor==2.2.0
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - torch==1.9.1
    - torchaudio==0.9.1
    - torchvision==0.10.1
    - tqdm==4.64.1
    - trio==0.22.2
    - trio-websocket==0.11.1
    - typer==0.9.0
    - tzdata==2022.7
    - tzlocal==4.2
    - ujson==5.7.0
    - virtualenv==20.17.1
    - webdriver-manager==4.0.1
    - websockets==10.4
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - wsproto==1.2.0
    - yarl==1.8.2
